theme: jekyll-theme-slate
google_analytics: UA-125020819-1
google_verify: Do0zrEK0ZiG8ICGamibbaonI3AYMDY31S9zxF8v1lr4

encoding: utf-8
plugins: 
  - jekyll-github-metadata
github : [metadata]
repository: Alalalalaki/UT_EH # 自分のアカウントとリポジトリを書きましょう

